name: Publish to PyPI

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    # Only run if the commit message contains [pypi]
    if: "contains(github.event.head_commit.message, '[pypi]')"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for version bumping
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install build tools
      run: |
        echo "[WORKFLOW] Installing build and publish dependencies..."
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: |
        echo "[WORKFLOW] Building package..."
        python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        echo "[WORKFLOW] Publishing to PyPI..."
        python -m twine upload dist/*
        echo "[WORKFLOW] Publish complete."